(Many) Patches
CriticalFlaw/flawhud pull request #497
Opened 2024-12-02 16:02 UTC by TheRSO

## Loadout panel changes
### Before (2560 x 1440 (16:9) only)
![](https://media.discordapp.net/attachments/991465089544761427/1313095024522821692/image.png?ex=674ee289&is=674d9109&hm=fba3c85c973086b8318ab4712bce78dd23e16877df9a42c07a1e24829cd8676d&=&format=webp&quality=lossless&width=802&height=451)![](https://media.discordapp.net/attachments/991465089544761427/1313095110090821675/image.png?ex=674ee29e&is=674d911e&hm=ec862ec34bd1fd05fcf040e837b16c24bd03faffb8672dbefd5ba4c6db6d12ab&=&format=webp&quality=lossless&width=802&height=451)

> [!NOTE] 
> Tried to align loadout and lower buttons using xpos p.[float] and regualar xpos, but couldnt align on both resolutions. The space in between the loadout buttons and from the left of the preset panel does not seem to behave nice. Button width stays unchanged between both resolutions.
### After
|  | **2560 x 1440 (16:9)** | **1440 x 1080 (4:3)** |
|--|--|--|
|  | ![](https://media.discordapp.net/attachments/991465089544761427/1313130076325281866/image.png?ex=674f032e&is=674db1ae&hm=a1244d22822edd4978d97067437a05aaad66edd12a6937d9889e9227f78e542d&=&format=webp&quality=lossless&width=802&height=451) | ![](https://media.discordapp.net/attachments/991465089544761427/1313131402543366164/image.png?ex=674f046b&is=674db2eb&hm=535c38edaa4146edd78890b2322db60841868b1d63f6a4781b00326b39cc86e2&=&format=webp&quality=lossless&width=802&height=602) |
|  | ![](https://media.discordapp.net/attachments/991465089544761427/1313130128125198336/image.png?ex=674f033b&is=674db1bb&hm=2c55015cf1c4ac8a8535fcd15a05c27d2daa823610f75141e705023d91452ec7&=&format=webp&quality=lossless&width=550&height=309) | ![](https://media.discordapp.net/attachments/991465089544761427/1313131445966864384/image.png?ex=674f0475&is=674db2f5&hm=b3584dacb0ef9d42cda19d565e67e9411f17d324de573f0f9f4b42b098d52a67&=&format=webp&quality=lossless&width=802&height=602) |
|  | ![](https://media.discordapp.net/attachments/991465089544761427/1313130404919775243/image.png?ex=674f037d&is=674db1fd&hm=ce76af533ee0bec15684c73991fa6c5d7e24a848f0c7622a3b43b1a1e50603e2&=&format=webp&quality=lossless&width=802&height=451) | ![](https://media.discordapp.net/attachments/991465089544761427/1313131937954660402/image.png?ex=674f04ea&is=674db36a&hm=7275f49abd212a3642e3bd68e2b3f65e2a97405c9fbe48f042056854d073e1f3&=&format=webp&quality=lossless&width=802&height=602) |
|  | ![]() | ![]() |

## Medigun/vacc charge moved down

### Before
![](https://media.discordapp.net/attachments/991465089544761427/1306586531770667008/image.png?ex=674e4748&is=674cf5c8&hm=b86745ebffe48814efe7c4435d080c66171408b25da897da18f3998734dd5a83&=&format=webp&quality=lossless)
![](https://media.discordapp.net/attachments/991465089544761427/1306586746229620746/image.png?ex=674e477b&is=674cf5fb&hm=92adae9d39a598dde6f06079ca9c4e4e85071960de26e07365044d4e2c4c2010&=&format=webp&quality=lossless)

### After
![](https://media.discordapp.net/attachments/991465089544761427/1313126875660423178/image.png?ex=674f0033&is=674daeb3&hm=043cfff776ad57a181d3b88894e6b8ce82514b9749458589836a4a867bfef4e5&=&format=webp&quality=lossless)
![](https://media.discordapp.net/attachments/991465089544761427/1313126971047149598/image.png?ex=674f004a&is=674daeca&hm=f87acccf74dc0fb5c9987bb7ecf7eeebc55a3f9b21379754d72687d4f8ce481d&=&format=webp&quality=lossless)

## Top bar changes
### Nudged top bar icons
**Left is after, Right is before**
![](https://media.discordapp.net/attachments/991465089544761427/1313124535087923220/image.png?ex=674efe05&is=674dac85&hm=ff87825b5856adf80b1c6e1de4d5c6c25e88ef09f2040a704e6ede4f671f0699&=&format=webp&quality=lossless&width=1253&height=384)
### Removed gradient, replace with plain bg
**Top is Before, bottom is after**
![](https://media.discordapp.net/attachments/991465089544761427/1313125054095032360/image.png?ex=674efe81&is=674dad01&hm=36de595ac1315277bba8ebfaece406cd51360836c47c2944ebde94eab49175f1&=&format=webp&quality=lossless&width=1253&height=120)**Contrast boosted**
![](https://media.discordapp.net/attachments/991465089544761427/1313129675366731837/image.png?ex=674f02cf&is=674db14f&hm=a142093e941b5aa9f9c1ed4896f64744b2d8d68ddf8971a851c6773d4ead383c&=&format=webp&quality=lossless&width=1253&height=278)
## Other
|  | Before | After |
|--|--|--|
|**Moved party chat left**| ![](https://cdn.discordapp.com/attachments/991465089544761427/1308037190214881300/image.png?ex=674e4850&is=674cf6d0&hm=b943d0a3575cec5b98f780447d7a812b6ea0e823810a8ca1d6b2affdd5346e6e) | ![](https://cdn.discordapp.com/attachments/991465089544761427/1313118405124952075/image.png?ex=674ef850&is=674da6d0&hm=323177d072a986cf33b69fc99ebe32f471b7f5927645c793547c350c39b7f555&) |
| **Brightened separator bar** | ![](https://media.discordapp.net/attachments/991465089544761427/1313096419682422804/image.png?ex=674ee3d6&is=674d9256&hm=c227e9f30310712715cc4c98eb8dea189bb9885fa3664107a7e7609c69a1ac3c&=&format=webp&quality=lossless) | ![](https://media.discordapp.net/attachments/991465089544761427/1313122234079903804/image.png?ex=674efbe1&is=674daa61&hm=0657036e18e0d1866c097eb6d5ec53e6655da9ec473a6382a5818df10d85a8e0&=&format=webp&quality=lossless) |
|**Nudged FL**|![](https://media.discordapp.net/attachments/991465089544761427/1313095684932505611/image.png?ex=674ee327&is=674d91a7&hm=90b6918d8671744225a3ea53052a377752a7c3235381079b9880cdc80ed6ca7c&=&format=webp&quality=lossless)|![](https://media.discordapp.net/attachments/991465089544761427/1313156031127228496/image.png?ex=674f1b5b&is=674dc9db&hm=ef008258c16c0890b82e9e1253fa21c4ff58f7110b38f1f5d0663a85b1eb7a72&=&format=webp&quality=lossless)|
| **Moved voices button next to text chat** | ![](https://media.discordapp.net/attachments/991465089544761427/1313118893727809577/image.png?ex=674ef8c4&is=674da744&hm=c42fa034d8ee2834939676780a6f5b670d3be61c62ae47da77ba22b6a52fc4ff&=&format=webp&quality=lossless&width=839&height=562) | ![](https://media.discordapp.net/attachments/991465089544761427/1313122019440722010/image.png?ex=674efbae&is=674daa2e&hm=0931f25af9a9d4f9e7b3bfc3002666356a7c9dd6bfba20aef0d0d3fa8ea221fe&=&format=webp&quality=lossless&width=837&height=562) |
| **Removed quit dialog border** | ![](https://media.discordapp.net/attachments/991465089544761427/1313133678557138944/image.png?ex=674f0689&is=674db509&hm=864aab4f1a34d14bcb6692c538f06dbf09401035460daee52be8590b49928c03&=&format=webp&quality=lossless) | ![](https://media.discordapp.net/attachments/991465089544761427/1313135043379462175/image.png?ex=674f07cf&is=674db64f&hm=51f123ee024652235ff573c6555d995baab3cab654f9773b370fc421dcb6f9a8&=&format=webp&quality=lossless) |
| **Nudged Killstreak Icon** | ![](https://media.discordapp.net/attachments/991465089544761427/1313162996771455019/image.png?ex=674f21d7&is=674dd057&hm=2b6269671c819266cbd457ead55c1a62e8d5237e68dbb58ae89293abb0c36361&=&format=webp&quality=lossless) | ![`](https://media.discordapp.net/attachments/991465089544761427/1313127341634879508/image.png?ex=674f00a2&is=674daf22&hm=dab780f721fe8007980da6c2f48bf5c1b4890ba4945b69ea50fd7e645fda4469&=&format=webp&quality=lossless) |
| **Hotfix for black bars** | ![](https://media.discordapp.net/attachments/991465089544761427/1313099111771410503/image.png?ex=674ee658&is=674d94d8&hm=cdbc19be9b0a69b41eb8412fb655c64e11b37d8e0caac4565e0afe62eb58931c&=&format=webp&quality=lossless&width=350&height=580) | ![](https://media.discordapp.net/attachments/991465089544761427/1313125958391300126/image.png?ex=674eff59&is=674dadd9&hm=3ee2657422673d0ef7bb0535d93dd2600f598852a1fab40673a9d166ea12caca&=&format=webp&quality=lossless&width=395&height=580) |
|  | | |

> [!NOTE] 
> Most of these changes were also checked on 4:3, but for sake of time/space, screenshots not included
> Pictures not to scale

2024-12-08 01:12 UTC, CriticalFlaw requested changes

2024-12-08 01:12 UTC, CriticalFlaw commented on resource/ui/classloadoutpanel.res
The `PassiveAttributes` change looks good but the class model changes don't translate well to lower 4:3 resolutions:
![20241207172443_1](https://github.com/user-attachments/assets/2cb46fc2-d9cd-4e9f-b3ff-ac3c8a3fa8ef)

What is the reason for updating the model position from the way it is today?

2024-12-08 01:12 UTC, CriticalFlaw commented on resource/ui/hudweaponselection.res
Can you post a screenshot of black bars before the fix and what resolution you've used to test this? I'm not able to reproduce this one on my side and don't recall it being reported before so I'm double checking to make sure this change is needed here.

2024-12-08 03:15 UTC, TheRSO commented on resource/ui/hudweaponselection.res
It’s at the bottom of PR comment.
![image](https://github.com/user-attachments/assets/be2c35aa-56b2-4378-8984-cea946b49d98)
It’s on 2560x1440 
I can check later on 1440x1080

2024-12-08 03:24 UTC, TheRSO commented on resource/ui/classloadoutpanel.res
2560x1440
![image](https://github.com/user-attachments/assets/40c82a6d-6116-473b-ac43-13750713ebcb)
[more on pr comment]

The current version uses Xpos to move it right, this has the consequence of making the player model clip off on the left side when you rotate it/or if the class model is big.

2024-12-08 03:34 UTC, TheRSO commented on resource/ui/classloadoutpanel.res
Will look into further when I get home.

2024-12-08 13:34 UTC, TheRSO commented on resource/ui/hudweaponselection.res
Changes for this res file reverted. I didn't check closely enough but bigger weapons ie minigun were getting cut off.

2024-12-08 13:55 UTC, TheRSO commented on resource/ui/classloadoutpanel.res
Off topic, but your 4:3 looks slightly dif 
(1440 x 1080)
![image](https://github.com/user-attachments/assets/3c10864d-1278-4232-8bf8-34119c39006e)

2024-12-08 16:07 UTC, TheRSO commented on resource/ui/classloadoutpanel.res
For the class model
```"wide"     "p[float]"``` --> 4:3 width is too small makes class model also small or 16:9 too big
```"wide"     "[int]"``` --> panel extends too far right interferes with buttons. 16:9 player model becomes small

also tried playing with model ```origin_xpos```, but that might be in HU, I'm not exactly sure, but it doesn't seem to scale with resolution.

prob will end up using custom class data due to pyro being extremely wide with stock flame compared to the tiny scout

2024-12-09 01:02 UTC, TheRSO commented on resource/ui/classloadoutpanel.res
@CriticalFlaw pushed another commit not sure how you feel but I sized pyro small so it wouldn't clip off if a player rotated him. 4:3 kind of forces me to have pretty limited space to work with on 16:9
this is 2560 x 1440 (16:9)
![image](https://github.com/user-attachments/assets/8c1734b6-7da0-445f-bb52-e9ea08f5a7b1)

1440 x 1080 (4:3)
![image](https://github.com/user-attachments/assets/0e8214af-1139-48d9-8463-87551b29e579)

2024-12-09 02:55 UTC, CriticalFlaw commented on resource/ui/classloadoutpanel.res
It appears too far the larger the resolution is. Maybe we revisit this particular one in a separate PR and merge the rest?
![20241208215440_1](https://github.com/user-attachments/assets/3234339c-518a-4bf6-af82-2ade77a7fe13)

2024-12-09 04:55 UTC, TheRSO commented on resource/ui/classloadoutpanel.res
can pin the panel to a anchor with p[float] as its xpos
```"xpos"     "c-[int]"``` on class model causes the model to stretch horizontally
there will have to be some level of compromise.

[clips but fov can be lowered]

## 2560 x 1080 
![image](https://github.com/user-attachments/assets/b2d1f6b3-9158-433e-a595-97954edf3669)
![image](https://github.com/user-attachments/assets/2b81db51-5cff-45a1-a592-43e91f1b0f87)
![image](https://github.com/user-attachments/assets/026ea2d0-6e34-4ac4-95ca-acb85b0980a2)


## 2560 x 1440
![image](https://github.com/user-attachments/assets/da85a6f4-193e-46ca-befc-1d3eaa427b5c)
![image](https://github.com/user-attachments/assets/fd0de6f7-d852-432c-a894-23b017acefb7)
![image](https://github.com/user-attachments/assets/5c071f63-b6cb-4008-9bea-6f88258342dd)


## 1440 x 1080
![image](https://github.com/user-attachments/assets/5c87ce85-85a0-4f61-8c77-9accd510793a)
![image](https://github.com/user-attachments/assets/a8acf63d-9fe9-41b3-9f8f-f1f4467b5ec4)
![image](https://github.com/user-attachments/assets/169737a8-768c-493b-b585-251ccefcc73e)

2024-12-09 06:08 UTC, TheRSO commented on resource/ui/hudweaponselection.res
ah I changed the tall value before by accident IC. It's looks fine now (model 80 x 50).

2024-12-09 18:23 UTC, CriticalFlaw commented on resource/ui/classloadoutpanel.res
The screenshots look pretty good to me. Could you commit that to this PR and I'll do a quick test after work?

2024-12-09 22:17 UTC, TheRSO commented on resource/ui/classloadoutpanel.res
@CriticalFlaw done

2024-12-10 02:59 UTC, CriticalFlaw commented
Looks and works great now. Really nice work. Thank you!

2024-12-10 03:00 UTC, CriticalFlaw approved these changes

2024-12-10 03:00 UTC, merged